issue-302: Added Spring boot/Lombok Annotations to the README.md
GalateaRaj/fuse-starter-java pull request #362
Opened 2021-12-21 16:29 UTC by RamiDaoud

issue-302: Added Spring boot/Lombok Annotations to the README.md

2021-12-21 17:35 UTC, cbaltera requested changes

2021-12-21 17:35 UTC, cbaltera commented on README.md
> +    - It is a method-level annotation. It is an alternative of XML <bean> tag. It tells the method to produce a bean to be managed by Spring Container.
Let's add a definition of "bean" here

2021-12-21 17:35 UTC, cbaltera commented on README.md
> +  - Allows Spring to automatically detect our custom beans. (For more visit https://www.baeldung.com/spring-component-annotation#component)
In particular, these are class-level annotations that will result in spring creating an instance of the class as a bean without us needing to define the bean in a configuration class

2021-12-21 17:35 UTC, cbaltera commented on README.md
> +    - It is a method-level annotation. It is an alternative of XML <bean> tag. It tells the method to produce a bean to be managed by Spring Container.
Also mention that we prefer using the stereotype annotations rather than defining beans in config classes where possible.

2021-12-21 17:35 UTC, cbaltera commented on README.md
> +    - It is used to map the web requests. It has many optional elements like consumes, header, method, name, params, path, produces, and value. We use it with the class as well as the method.
... map the web requests, i.e. translate between a url path like fuse.domain/endpoint?param=value and the endpoint method that will handle it.

2021-12-21 17:35 UTC, cbaltera commented on README.md
> +  - Lombok Annotations:
can we have a sentence here about lombok letting us avoid boilerplate code?

2021-12-21 17:39 UTC, cbaltera commented
@GalateaMattB does this cover what you were looking for?

2021-12-22 11:24 UTC, RamiDaoud commented
> @GalateaMattB does this cover what you were looking for?

Please refrence https://docs.google.com/document/d/1eNODztmE8VPgQ8sEs-QyGH5rjXgx_2esnp5cJK2YF7Q/edit#heading=h.gy2hov5n7fcf for a more verbose explanation.

2021-12-22 21:49 UTC, cbaltera commented on README.md
> +    - It is a method-level annotation. It is an alternative of XML <bean> tag. It tells the method to produce a bean to be managed by Spring Container.
Good start, but what if we have a new joiner with no java experience? Maybe a link to https://www.baeldung.com/spring-bean would help

2021-12-22 21:52 UTC, cbaltera commented on README.md
> +    - It is a method-level annotation. It is an alternative of XML <bean> tag. It tells the method to produce a bean to be managed by Spring Container.
ah, github wasn't showing me the latest changes -- looks good, but let's add the link anyway

2026-04-09 05:20 UTC, closed without merging